### ISSUE TITLE
Fix the file path which is going to be signed

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-app#112]
The commit d244fd3 ("CI: Lift Kolibri's path to Endless Key app's root path") moves the original `kolibri-windows/resources/app/src/Kolibri/Kolibri.exe` to `kolibri-windows/Kolibri/Kolibri.exe`.  The sign_binaries_for_EK_USB_image job fails, because the path has not been updated, too.

**Comment by starnight** [comment]
This can be verified by triggering [Tag Weekly](https://github.com/endlessm/endless-key-app/actions/workflows/tag.yml) CI.

**Comment by dbnicholson** [comment]
The job [still failed](https://github.com/endlessm/endless-key-app/actions/runs/5049617230) but with a 401 uploading to Microsoft Store. It seems unrelated, but I'm going to reopen this for now.

**Comment by starnight** [comment]
The [action](https://github.com/endlessm/endless-key-app/actions/runs/5049617230)'s sign_binaries_for_EK_USB_image job works successfully.  So, I close this issue.

Then, split the failed "uploading to Microsoft Store" as **Fix MS Store Broker Authentication setting failure** #114
