### ISSUE TITLE
Synchronizing the number part of kolibri-explore-plugin's release into APPX's version number

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-app#119]
This issue comes from the discussion: https://github.com/endlessm/kolibri-explore-plugin/pull/564#discussion_r1217962805

Here is the background information:
* Microsoft defines MSIX/APPX's version number as `Major.Minor.Build.Revision`.
https://github.com/microsoft/WindowsAppSDK/blob/main/specs/Deployment/MSIXPackageVersioning.md#122-version-number--msix
* Endless Key app (Android) has the version like Ladybird 6.2-329
  * "Ladybird" comes from the [VERSION file of kolibri-explore-plugin](https://github.com/endlessm/kolibri-explore-plugin/blob/master/kolibri_explore_plugin/VERSION)
  * 6.2 is the [tag of kolibri-explore-plugin](https://github.com/endlessm/kolibri-explore-plugin/tags) minus the patch (we don't use patch number)
  * 329 is the Android specific version

For Endless Key app (Windows), we can update versioning:
* sync the Major and Minor as kolibri-explore-plugin's tag minus the patch
* Build: increase number simply for Windows app build
* Revision: is `0`

**Comment by manuq** [comment]
Good! As I said in https://github.com/endlessm/kolibri-explore-plugin/pull/564#discussion_r1219447129 I wouldn't tie the app version to kolibri-explore-plugin entirely. But keeping the "Build" part for changes that don't affect the plugin sounds like a good plan!

**Comment by starnight** [comment]
The tag string uses kolibri-explore-plugin's release https://github.com/endlessm/endless-key-app/actions/runs/5384111696/jobs/9771645041

**Comment by vanessa-chang** [comment]
It's verified passed as the Appx' version contains the Kolibri-explore-plugin version
