### ISSUE TITLE
Update to Kolibri v0.16.0-alpha15 

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-app#120]
Adds the ability to include thumbnails for content items with the metadata.

**Comment by erikos** [comment]
https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha15

**Comment by wjt** [comment]
Like 5ccaf93a274fe394885666a40e7f06dcc3c37769 with a different integer

**Comment by erikos** [comment]
The latest one v6.10.0.0 is on MS store's Alpha test flight.
