### ISSUE TITLE
PDF files are not well presented on Aspire A514-55G

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-app#133]
So far, this issue only happens on an Aspire A514-55G.
E406MA cannot reproduce this issue.
This issue cannot be reproduced if the same content is opened by a browser. 

Test version: 6.23.1.0

<img width="498" alt="Screenshot 2023-06-26 191137" src="https://github.com/endlessm/endless-key-app/assets/31236978/b20df73e-bd83-46fb-a4f0-e1a960da3b5f">

**Comment by wjt** [comment]
Our best theory about what was different about this system is that it has an NVidia GPU.

We could try updating Electron.

Another longer-term approach would be to rewrite the app to use WebView2 since it works in Edge (which is the same code) on the same device.

**Comment by starnight** [comment]
@vanessa-chang has help test the build from https://github.com/endlessm/endless-key-app/pull/140.  But, this issue still can be reproduced, even Electron is updated to 22.3.16.

**Comment by vanessa-chang** [comment]
It works with the new test package from: https://github.com/endlessm/endless-key-app/actions/runs/6532523862

**Comment by vanessa-chang** [comment]
It works with the latest package in alpha flight
