### ISSUE TITLE
Windows: Bump Kolibri to 0.16-alpha18

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-app#134]
It has been released: https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha17

From Richard:
> Flagging that once again the mac app notarization has messed up the asset upload. The assets can still be found in the artifacts for the release action here: https://github.com/learningequality/kolibri/actions/runs/5378800426 (with the same caveat as last time that they are zipped).

**Comment by wjt** [comment]
I suggest we wait for -alpha18 to get the fix for https://github.com/learningequality/kolibri/pull/10912

**Comment by wjt** [comment]
Unfortunately this doesn't work. When I first upgraded my existing install of the app to the test build from #137, it came up like this, with an empty Discovery section:

![Screenshot 2023-07-06 065804](https://github.com/endlessm/endless-key-app/assets/86760/2151ad80-9e40-4085-82d6-d8cd95f66f23)

I have now erased the app data and am re-downloading a starter pack to see what happens.

**Comment by wjt** [comment]
Rather annoyingly it works perfectly and I didn't save the offending broken state.

**Comment by pwithnall** [comment]
Unassigning myself as I don’t have a Windows machine to verify things on.

**Comment by vanessa-chang** [comment]
Verified passed on the test build: v6.24.1.0

Release: Ladybird v6.24.0
Kolibri: 0.16.0a18
