### ISSUE TITLE
Prototype moving the front-end of Endless Key app (Windows) from Electron to pywebview

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-app#138]
We have tested a simple [pywebview](https://pywebview.flowrl.com/) application on Windows in [EK Windows app: Test pywebview as the frontend](https://phabricator.endlessm.com/T34722).  It works and reduces a lot of size by using the native webview from system.

We can run the pywebview window accessing the kolibri server which runs in another [thread](https://docs.python.org/3/library/threading.html).

Also, have to take care some known things:
* The environment variables setup [kolibri-electron/src/index.js](https://github.com/endlessm/endless-key-app/blob/v6.24.1/kolibri-electron/src/index.js)
* The content source selection [kolibri-electron/src/preload.js](https://github.com/endlessm/endless-key-app/blob/v6.24.1/kolibri-electron/src/preload.js)

**Comment by wjt** [comment]
We might hope that this would fix #133 – this could be something we could quickly prototype with a simple application that just uses pywebview and accesses key.endlessos.org

**Comment by starnight** [comment]
Have a simple PyWebview application browsing https://key.endlessos.org
1. Prepare `main.py` on Windows as:
```python
#!/bin/env python3

import tempfile
import webview

PYWEBVIEW_DATA=tempfile.gettempdir() + "/pywebview"

webview.create_window('Hello world', 'https://key.endlessos.org')
webview.start(storage_path=PYWEBVIEW_DATA)
```
2. Install pyinstaller & pywebview: `python -m pip install pywebview pyinstaller`
3. Compile main.py as a single executable file: `python -m PyInstaller -F .\main.py`
4. The built file is `.\dist\main.exe`  [main.zip](https://github.com/endlessm/endless-key-app/files/12000971/main.zip)

![Image](https://github.com/endlessm/endless-key-app/assets/2100946/6166d3ce-f140-4147-9b60-f0061edf56ce)

**Comment by wjt** [comment]
With this prototype app, can you test on Vanessa's laptop whether #133 is reproducible?

Then take a brief look at how to start up both a webview and the Django backend. Although it would be neater in some ways to run the two parts in one process, I'm not totally convinced that running the webview and the Django service in threads of the same process is wise. Python has a [global interpreter lock](https://en.wikipedia.org/wiki/Global_interpreter_lock) which prevents it making good use of multiple threads. (In this case it may be a non-issue because the web view is native code (not bound by the GIL) and presumably uses a separate process for rendering anyway.)

**Comment by vanessa-chang** [comment]
Tried the main.zip, the issue of the read content presentation is not reproduced. (tried the content from 49er & wikihow)

**Comment by starnight** [comment]
> Tried the main.zip, the issue of the read content presentation is not reproduced. (tried the content from 49er & wikihow)

Ya!  Thanks!  That encourages me to do next step!

**Comment by starnight** [comment]
> I'm not totally convinced that running the webview and the Django service in threads of the same process is wise. Python has a [global interpreter lock](https://en.wikipedia.org/wiki/Global_interpreter_lock) which prevents it making good use of multiple threads. (In this case it may be a non-issue because the web view is native code (not bound by the GIL) and presumably uses a separate process for rendering anyway.)

The main process is the "Hellow world", and "Microsoft Edge Webview2"s are sub-processes 
![image](https://github.com/endlessm/endless-key-app/assets/2100946/8ca9f97e-f184-4402-98d1-6bbd2aa1761a)

**Comment by starnight** [comment]
Have the new endless-key-app branch [test-pywebview](https://github.com/endlessm/endless-key-app/tree/test-pywebview).

Follow the [build steps](https://github.com/endlessm/endless-key-app/blob/e1382ea07409f93274eb8c5652994581ad285a8e/.github/workflows/main.yml#L42-L87) to prepare the endless-key-app src with PyWebview.

Then, get into the src folder & `python.exe main.pyw`.  It works as following pictures:

![image](https://github.com/endlessm/endless-key-app/assets/2100946/3323c195-b3bf-4fb1-a28b-a1e96a5cc9e9)
![image](https://github.com/endlessm/endless-key-app/assets/2100946/5a559f51-634f-4e54-a88c-9498b082f264)
![image](https://github.com/endlessm/endless-key-app/assets/2100946/ed71c67f-e430-40ea-8a17-2a6c15447506)
![image](https://github.com/endlessm/endless-key-app/assets/2100946/989408d6-37c2-431e-9e10-e422679f22e6)
![image](https://github.com/endlessm/endless-key-app/assets/2100946/98422d5c-0be9-46c9-8da1-0b4a76cc2d51)
![image](https://github.com/endlessm/endless-key-app/assets/2100946/9d6bfde7-9179-4e6e-91b2-c88c93688776)

This is a quick prototype without Endless USB key feature.  Besides, it does not handle closing thread of kolibri server properly.  But, the happy path works at least.

**Comment by starnight** [comment]
I think current [test-pywebview](https://github.com/endlessm/endless-key-app/tree/test-pywebview) branch can call this done.  However, when we are going to change Electron to PyWebview, here are some items we have to take care:
* PyWebview uses system native webview library.  We have to detect system's native webview is installed, or not.  Windows document shows [Detect if a suitable WebView2 Runtime is already installed](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed).
* To compatible with original **kolibri-electron.exe**'s home directory and upgradable, the new PyWebview's executable binary name should be same as **kolibri-electron.exe**.
* Take care more environment variables stuff, but may be just these if [Remove the option to use a physical key with the app](https://github.com/endlessm/kolibri-explore-plugin/issues/723) happens.
* Use callback function when Kolibri backend is ready, instead of waiting by sleep.
* Find the way to close Kolibri backend gently when the web view is closed.
* Build as a single **.exe** file, or separately files like current version?

**Comment by wjt** [comment]
> * To compatible with original **kolibri-electron.exe**'s home directory and upgradable, the new PyWebview's executable binary name should be same as **kolibri-electron.exe**.

Why is it necessary for the binary to have the same name?

**Comment by starnight** [comment]
> > * To compatible with original **kolibri-electron.exe**'s home directory and upgradable, the new PyWebview's executable binary name should be same as **kolibri-electron.exe**.
> 
> Why is it necessary for the binary to have the same name?

Good question!

All about the `HOME` directories:
* Current Endless Key app (Windows)'s `HOME` directory is `C:\Users\dev\AppData\Local\Packages\EndlessOSFoundation.EndlessKey_bt8q3zn5k2ahy\`.
* The entry point of current Endless Key app (Windows) is [**kolibri-electron.exe**](https://github.com/endlessm/endless-key-app/blob/v6.31.2/build_winapp/appxmanifest.xml#L33).  So, its `HOME` directory is `C:\Users\dev\AppData\Local\Packages\EndlessOSFoundation.EndlessKey_bt8q3zn5k2ahy\LocalCache\Roaming\kolibri-electron\`.
* Kolibri process is [forked](https://github.com/endlessm/endless-key-app/blob/v6.31.2/kolibri-electron/src/index.js#L298) from **kolibri-electron.exe** and stores the DB files in its `HOME` directory `C:\Users\dev\AppData\Local\Packages\EndlessOSFoundation.EndlessKey_bt8q3zn5k2ahy\LocalCache\Roaming\kolibri-electron\endless-key`:
```
PS C:\Users\dev> ls C:\Users\dev\AppData\Local\Packages\EndlessOSFoundation.EndlessKey_bt8q3zn5k2ahy\LocalCache\Roaming\kolibri-electron\endless-key\


    Directory: C:\Users\dev\AppData\Local\Packages\EndlessOSFoundation.EndlessKey_bt8q3zn5k2ahy\LocalCache\Roaming\kolibri-electron\endless-key


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          8/7/2023   1:41 PM                content
d-----          8/7/2023   1:41 PM                logs
d-----          8/7/2023   1:41 PM                process_cache
d-----          8/7/2023   1:51 PM                sessions
-a----          8/7/2023   1:41 PM              8 .data_version
-a----          8/7/2023   1:55 PM       28114944 db.sqlite3
-a----          8/7/2023   1:51 PM          32768 db.sqlite3-shm
-a----          8/7/2023   1:57 PM        2418472 db.sqlite3-wal
-a----          8/7/2023   1:58 PM         143360 job_storage.sqlite3
-a----          8/7/2023   1:41 PM          40960 networklocation.sqlite3
-a----          8/7/2023   1:41 PM          36864 notifications.sqlite3
-a----          8/7/2023   1:41 PM           9904 options.ini
-a----          8/7/2023   1:41 PM           1468 plugins.json
-a----          8/7/2023   1:41 PM          40960 syncqueue.sqlite3
```
To make it upgradable and keep the DB files , we have to follow the pattern `Roaming\kolibri-electron\endless-key`

**Comment by starnight** [comment]
> * PyWebview uses system native webview library.  We have to detect system's native webview is installed, or not.  Windows document shows [Detect if a suitable WebView2 Runtime is already installed](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed).

We can make **WebView2** as the dependency in `appxmanifest.xml`.  Document [win32dependencies:ExternalDependency (Windows 10, Windows 11)](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency#examples) shows the example.  Then, system will take care Endless Key app's WebView2 dependency automatically.

**Comment by starnight** [comment]
#141 finished this!  Ya!
