### ISSUE TITLE
Replace Electron with PyWebview for Endless Key App

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-app#141]
We have:
* Tested a simple pywebview application on Windows in [EK Windows app: Test pywebview as the frontend](https://phabricator.endlessm.com/T34722).  It works and reduces a lot of size (about 100 MB) by using the native webview from system.
* Directed the simple pywebview application browsing https://key.endlessos.org in [Prototype moving the front-end of Endless Key app (Windows) from Electron to pywebview](https://github.com/endlessm/endless-key-app/issues/138).
  - We notice Webview2 used by PyWebview on Windows can render PDF files with NVIDIA card correctly.  However, current Endless Key app uses the webview provided by Electron, but hits [PDF files are not well presented on Aspire A514-55G](https://github.com/endlessm/endless-key-app/issues/133) eqiupped with NVIDIA card.
  - The main Python is the main process.  The Webview2 used by PyWebview will be the sub-process browsing a web page.  So, that avoids Python's GIL issue between the Python application and the Webview2.

More benefits:
* Webview2 is the native webview from Windows.  It has better compatibility with the hardware resource provided by the system.
* PyWebview is a Python library briding between Python application and native webview from system.  The dependency can be set in the Pipfile directly, just like other Python package.  Then, we can drop node.js and Electron which reduces maintenance and CI complexity.

The original Endless Key app is executed by running **kolibri-electron**, which is an Electron app.
1. Show the maximized webview window and browsing [kolibri_explore_plugin's welcomeScreen](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L257).
2. Check `KOLIBRI_HOME` is created, or not.
  * If not, then this is a fresh run.  Show [`WelcomeApp.showWelcome()`](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L260C47-L260C71).  Then, choose the content from USB, or download from server.  Here goes another code branch first.  More ...
  * If yes, then [check it should read content from Endless USB key, or not](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L261C20-L261C39).
    - If not, [ask user plug Endless USB key](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L262)
    - If yes, next step.
3. Run kolibri server at backend.  But, frontend has to [wait kolibri server up](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L209).
4. If kolibri server is ready, then [change frontend to Kolibri's explore](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L217-L218).  Finally, frontend works with kolibri server.

Here lists some key tech for transferring to PyWebview:
* IPC bewteen frontend and Python application: [PyWebview's Javascript API](https://pywebview.flowrl.com/examples/js_api.html)
* Change webview's browsing URL: [PyWebview's Change URL](https://pywebview.flowrl.com/examples/change_url.html)
* Ask webview execute js from Python: [PyWebview's API evaluate_js](https://pywebview.flowrl.com/guide/api.html#evaluate-js)
* HTTP client request: https://docs.python.org/3/library/http.client.html

**Comment by starnight** [comment]
## Prototype the happy path without USB feature (2 weeks)

This could be tracked in [Prototype moving the front-end of Endless Key app (Windows) from Electron to pywebview](https://github.com/endlessm/endless-key-app/issues/138)

* Set up kolibri with kolibri-explore-plugin and collection environment locally.
* PyWebview browsing [kolibri_explore_plugin's welcomeScreen](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L257)
* Gather environment variables for running Kolibri backend
*  Assume this is a fresh run. Show [WelcomeApp.showWelcome()](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L260C47-L260C71). And, run kolibri server at backend with another thread.

## Check `KOLIBRI_HOME` is created (2 days)

This follows previous prototype.  With this feature, no more download action if `KOLIBRI_HOME` is created.

## Add Endless USB key feature (1 week)

* [Require Endless USB key?](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L261)
* [Detect USB state changes](https://github.com/endlessm/endless-key-app/blob/v6.27.1/kolibri-electron/src/index.js#L193C7-L193C23)
* Integrate the USB features into prepare running Kolibri backend process

## Integrate CI (3 days)

This is more related to [build](https://github.com/endlessm/endless-key-app/blob/v6.27.1/.github/workflows/main.yml#L16) and [packaging](https://github.com/endlessm/endless-key-app/blob/v6.27.1/build_winapp/appxmanifest.xml#L33)

**Comment by starnight** [comment]
Thanks to:
* #145
* endlessm/kolibri-explore-plugin/issues/748

The porting becomes simpler.

PR #161 is ready for review now.

**Comment by starnight** [comment]
During the test, I notice pywebview (system's webview) will create cookies' stoarage path in C:\Users\<user>\Appdata\Roaming\kolibri-electron\endless-key\, not the APPX/MSIX package's mapped virtual path C:\Users\<user>\AppData\Local\Packages\EndlessOSFoundation.EndlessKey_xxxooooxxx\LocalCache\Roaming\kolibri-electron\endless-key.  I am preparing another commit to fix it.

Pywebview still work as expected, just try to fix the cookies' storage path.

**Comment by erikos** [comment]
Testing results are looking very promising for this one. I was able to use the app fine in Windows 11, using the build [artifact](https://github.com/endlessm/endless-key-app/actions/runs/6532523862).

**Comment by manuq** [comment]
This is ready to be deployed.

**Comment by vanessa-chang** [comment]
Verified Passed in Windows 7.8.3.0
