### ISSUE TITLE
Windows: Spanish setting only applies on the loading screen

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-app#158]
From @vanessa-chang at https://github.com/endlessm/kolibri-explore-plugin/issues/861

In the latest Windows app: 7.4.1.0

OS language settings
<img width="365" alt="Captura de pantalla 2023-09-28 202440" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/7f791880-5352-4f02-ac7c-4f734fd38c68">

The loading screen is in Spanish but the following screens are still in English.

<img width="960" alt="Captura de pantalla 2023-09-28 201223" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/441d31c9-f395-4d68-8088-6b06c550acc6">
<img width="960" alt="Captura de pantalla 2023-09-28 201251" src="https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/65ace7d4-15de-479d-bf77-47a1bc008d69">

**Comment by manuq** [comment]
I have opened a PR that is basically a port of (part of) https://github.com/endlessm/kolibri-installer-android/pull/188 . Please note that existing installations would still be in English. Further work is needed for fixing that (add a "Windows plugin" like we have in Android, add a migration script).

**Comment by erikos** [comment]
> I have opened a PR that is basically a port of (part of) [endlessm/kolibri-installer-android#188](https://github.com/endlessm/kolibri-installer-android/pull/188) . Please note that existing installations would still be in English. Further work is needed for fixing that (add a "Windows plugin" like we have in Android, add a migration script).

Nice, thanks a lot! I think the migration could come in a second step, would not block on it.

**Comment by erikos** [comment]
Works fine in 7.10.427 - QA pass.
