### ISSUE TITLE
The CI pushes to MS store failed, because of lacking 01-EK-Screenshot-ES@1.5x.png

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-app#169]
The StoreBroker pushes Endless Key package to MS store failed.  Here is the error:
```
Write-Error: C:\Users\runneradmin\Documents\PowerShell\Modules\StoreBroker\1.21.0\StoreBroker\PackageTool.ps1:3760
Line |
3760 |          Write-Log -Exception $_ -Level Error
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 2023-11-15 16:53:01 : runneradmin :  Write-Log:
     | C:\Users\runneradmin\Documents\PowerShell\Modules\StoreBroker\1.21.0\StoreBroker\PackageTool.ps1:1279 Line |
     | 1279 |          Write-Log -Message $output -Level Error      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
     | | 2023-11-15 16:53:00 : runneradmin : Could not find media file [01-EK-Screenshot-ES@1.5x.png] in any
     | subdirectory      | of [D:\a\endless-key-app\endless-key-app\MSAppPayload\PDPs\20231115\es-419].
```
https://github.com/endlessm/endless-key-app/actions/runs/6880285674/job/18714438044#step:5:445

**Comment by starnight** [comment]
I follow the steps in [Create and push the Application Payload to Package Flight on Microsoft store](https://github.com/endlessm/endless-key-app/blob/7860152dd486baa8f0445d34f2de970754143981/.github/workflows/main.yml#L369-L391) to get "PDP.xml"s (renamed as PDP.txt for uploading)
* en-us: [PDP.txt](https://github.com/endlessm/endless-key-app/files/13856636/PDP.txt)
* es-419: [PDP.txt](https://github.com/endlessm/endless-key-app/files/13856634/PDP.txt)

Then, I notice we [only deal the en-us version](https://github.com/endlessm/endless-key-app/blob/7860152dd486baa8f0445d34f2de970754143981/.github/workflows/main.yml#L394-L424), but miss es-419 one.

**Comment by starnight** [comment]
The CI pushes the package to MS store now https://github.com/endlessm/endless-key-app/actions/runs/7500867509

**Comment by vanessa-chang** [comment]
v7.12.2 is now in the alpha flight branch. However, it will be blocked if the Avira antivirus is installed.
Waiting for v7.12.3 to verify again.
